---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.2

suites:
  - name: default
    run_list:
      - recipe[codenamephp_mysql::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
