sudo: required
dist: trusty

services: docker

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
    - ENV=CI
      
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
   
  - script:
    - chef exec berks install
    - chef exec rake
      
notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb
