language: ruby
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  
services: docker

env:
  global:
    - ENV="ci"
    - secure: "d9z1iUX8c3bMiTdYspOPaSOqMCBnVS4lts3Hns57OWajpmYrPC28uZW9a10Fi1mLnJKY7zdFPIDDQJLxFe4IL3DuUQsPcM/xAj5g4IFXTy1PBXnzODftllhqhVG0fa8U+VkqeEhSsTJXGP6hvObPfwj6Ov71yiwoUe6lvRLeWjbwJR4TMBz8a+fjXV1Zc/UnHiJEW7AssG+GfBPSzYJg6TzeFNwV0NqhPN9qnJkgsaizoZ6EGkeZ1i0e5889GgHTT3O/IwRfZONZmalx3sXi4MKwMpX7nXO8FI2B22LUML/tWr6NtiJGuRdzEA9eZd9aLxQb0txfQcxi0nyVOUCbomNtpk38jXj1R1RfgXH9W2lbg52C47jZtXClf6eHZUAvJj7WxQA/6PAspCEpGB8kGhGOpqUl6OhkBNtkImIGbWVI5L7eeDBDiKwJQnBG9qhRha3+PBPCrLOzDeOPAlXDO9JIBrUT3oknVxe0ae2+6kzdE2O0NzAZmeOQFU04kCozL17Q/UaeuULSLoE3tOnStwoRVYq9QhqGfu7TYvwRPu79efWpIs+6SR8ZEYIaFGctfp6OO2TyVlI2JHYbYTCAhoMU3gdakoZQkSRbC4sF+QD7BRXSz8hUIptE1Gb0MS6cs9NF/FKi3eJEa/g9PMYez/PgKlq7cH+Qus+0OKAIfwI="
addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - openssl aes-256-cbc -K $encrypted_4c0189a98bd3_key -iv $encrypted_4c0189a98bd3_iv -in codenamephp.pem.enc -out codenamephp.pem -d
  - gem install github_changelog_generator

script:
  - chef exec rake ci
  
deploy:
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: chef exec rake release
  
notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb

  