sudo: required
dist: trusty

services: docker

env:
  - ENV="ci"

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  
install: 
  - chef exec bundler install
  - chef exec berks install
   
script:
  - chef exec rake

before_deploy:
  - openssl aes-256-cbc -K $encrypted_08601d0550bd_key -iv $encrypted_08601d0550bd_iv -in codenamephp.pem.enc -out codenamephp.pem -d

deploy:
  provider: script
  script: chef exec rake release
  on: tags

notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb
