language: ruby
sudo: required
dist: trusty

services: docker

env:
  global:
    - ENV="ci"

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
install:
  - chef exec bundler install
  - chef exec berks install
script:
  - chef exec rake
  
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4c0189a98bd3_key -iv $encrypted_4c0189a98bd3_iv -in codenamephp.pem.enc -out codenamephp.pem -d
deploy:
  - provider: chef-supermarket
    user_id: "codenamephp"
    client_key: "codenamephp.pem"
    on:
      tags: true
  - provider: script
    script: chef exec rake release
    on:
      tags: true
  
notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb
