sudo: false
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: true

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/bin/chef exec berks install
  - /opt/chefdk/bin/chef exec foodcritic .
  - /opt/chefdk/bin/chef exec rspec
  - /opt/chefdk/bin/chef exec kitchen test